// GENERATED by scripts/generate-content-manifest.ts — do not edit by hand.
// Git-side content ids the Sanity Studio bundle needs but can't read from disk.
// Regenerated at predev/prebuild; committed so builds work without a prior run.

/** Reading chapter ids (a Scene's `beatRef` for `beat: 'reading'`). */
export const READING_BEATS: readonly string[] = ['00-prologue', '01-chapter-one'];
