// Build-time generator for the Studio content manifest. Sanity Studio runs in
// the browser and can't read the git content tree, so it can't tell which
// chapters / timeline beats still lack Scene art (the beats live in git, the
// art lives in Sanity). This emits the git-side beat ids into a plain TS module
// the Studio bundle can import, powering the per-beat "Scene art" coverage panes
// in `src/sanity/structure.ts`. Runs at predev/prebuild alongside
// `copy-content-media.mjs`; the output is committed so tsc/CI/build work
// without a prior generator run, and regenerated here to stay current.
//
// Uses the shared content engine (`contentCore`) so slug = filename rules and
// Zod validation match the Next app (CAND-05).
import fs from 'node:fs';
import path from 'node:path';
import { getReadingEntries, getTimelineEntries } from '../src/lib/contentCore';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'src', 'sanity', 'content-manifest.ts');

/** Beat ids — same value a Scene's `beatRef` must carry. Include drafts so
 *  Studio coverage reflects every file on disk. Sorted for a deterministic
 *  committed manifest. */
const readingBeats = getReadingEntries('include')
  .map((e) => e.id)
  .sort();
const timelineBeats = getTimelineEntries('include')
  .map((e) => e.id)
  .sort();

// Emit oxfmt-friendly arrays: short lists stay one line; longer lists wrap
// with a trailing comma per item (matches `oxfmt --check` on the committed file).
function emitArr(beats: string[]): string {
  if (beats.length <= 2) {
    return `[${beats.map((b) => `'${b}'`).join(', ')}]`;
  }
  return `[\n${beats.map((b) => `  '${b}',`).join('\n')}\n]`;
}
const body = `// GENERATED by scripts/generate-content-manifest.ts - do not edit by hand.
// Git-side content ids the Sanity Studio bundle needs but can't read from disk.
// Regenerated at predev/prebuild; committed so builds work without a prior run.

/** Reading chapter ids (a Scene's \`beatRef\` for \`beat: 'reading'\`). */
export const READING_BEATS: readonly string[] = ${emitArr(readingBeats)};

/** Timeline event ids (a Scene's \`beatRef\` for \`beat: 'timeline'\`). */
export const TIMELINE_BEATS: readonly string[] = ${emitArr(timelineBeats)};
`;

fs.writeFileSync(OUT, body);
console.log(
  `[content-manifest] wrote ${readingBeats.length} reading + ${timelineBeats.length} timeline beat(s) → ${path.relative(ROOT, OUT)}`,
);
